### ISSUE TITLE
Please support SSR (server side rendering) - ReferenceError: window is not defined

### ISSUE THREAD

**Issue by AnthonyNahas** [thatisuday/ngx-image-gallery#10]
hi,

i am using the module in my angular v4 app that will be rendered on the server side with nodejs.
Since in NodeJS there is not a window object, document... when i add this module to the app my build crashes!

Error: -->

```
})(window, document, 'Hammer');
   ^

ReferenceError: window is not defined
    at Object.VERSION
```

Angular V 4.4.6
Node V 8.9.1

Thank you in advance

**Comment by thatisuday** [comment]
I will have a look into it but I am not expert in Server side rendering. If you know where the problem is, give me a PR.

**Comment by AnthonyNahas** [comment]
I found the problem --> **`hammer.js`** should be imported in main.ts and not within your module

**Comment by AnthonyNahas** [comment]
#12
