### ISSUE TITLE
sanitizing unsafe style value url(SafeValue must use [property]=binding: url('blob:http://localhost:4200/e295517e')

### ISSUE THREAD

**Issue by makkasi** [thatisuday/ngx-image-gallery#18]
`sanitizing unsafe style value url(SafeValue must use [property]=binding: url('blob:http://localhost:4200/e295517e')`

@thatisuday @AnthonyNahas 
I have problem using images that are just uploaded in the memory. I have tried to sanitize with:
`this._images.push({
            url: this.sanitizer.bypassSecurityTrustUrl(URL.createObjectURL(file)),
            altText: file.name,
            title: file.name,
          });`

but the url property have to be string and the sanitizer returns SafeUrl. Using only the `URL.createObjectURL(file)` doesn't work as well.

**Comment by thatisuday** [comment]
I never tested this module with blob or base64. I guess I have to look into i.

**Comment by andyrue** [comment]
@makkasi Did you find a way to make this work?

**Comment by makkasi** [comment]
No, I end up creating my simple gallery.

**Comment by NimaiUser** [comment]
Any one fix this issue?
