### ISSUE TITLE
Adding right panel next to images

### ISSUE THREAD

**Issue by sonnyk22** [thatisuday/ngx-image-gallery#31]
Excellent library!!!

Is there a way to add a right panel next to show images such as shown in Figure below?

![untitled](https://user-images.githubusercontent.com/6744710/44240524-9ad5db00-a18c-11e8-9074-8e3c39047d54.png)

Thank you!

**Comment by yglodt** [comment]
You can do that independently of ngx-image-gallery in your html layout

**Comment by sonnyk22** [comment]
Followed your advise and got it working great.  Thank you!
