### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by VladimirValov** [thatisuday/ngx-image-gallery#54]
![Screenshot from 2020-02-21 15-58-37](https://user-images.githubusercontent.com/21157352/75040425-52a32180-54c3-11ea-85d2-00ec224767e0.png)

`ERROR in node_modules/ngx-image-gallery/index.d.ts:5:22 - error NG6002: Appears in the NgModule.imports  , but could not be resolved to an NgModule class

5 export declare class NgxImageGalleryModule{`

**Comment by sinbads5** [comment]
I was able to upgrade here https://github.com/sinbads5/ngx-image-gallery

**Comment by VladimirValov** [comment]
@sinbads5 can you create pull request or publish to npm? @thatisuday please merge it.

**Comment by sinbads5** [comment]
@VladimirValov @thatisuday pull request created.

**Comment by flepault** [comment]
Pull request has been merged, but i still have the problem? Is it solved ?

**Comment by varminas** [comment]
With Angular 9.0.6 and ngx-image-gallery@2.0.1 I get this error message:
 
    ERROR in node_modules/ngx-image-gallery/dist/index.d.ts:5:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ngx-image-gallery) which declares NgxImageGalleryModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    5 export declare class NgxImageGalleryModule {

**Comment by shaunberkley** [comment]
> With Angular 9.0.6 and ngx-image-gallery@2.0.1 I get this error message:
> 
> ```
> ERROR in node_modules/ngx-image-gallery/dist/index.d.ts:5:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> 
> This likely means that the library (ngx-image-gallery) which declares NgxImageGalleryModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 
> 5 export declare class NgxImageGalleryModule {
> ```

I'm getting the same error. Any chance this can be fixed?

**Comment by thatisuday** [comment]
**v2.0.3** should fix this.

**Comment by shaunberkley** [comment]
> **v2.0.3** should fix this.

This works now. Thank you!
