### ISSUE TITLE
Close gallery on outside click of image

### ISSUE THREAD

**Issue by thatisuday** [thatisuday/ngx-image-gallery#8]

**Comment by vidicj** [comment]
Hello thatisuday,

Was this feature implemented? 
I couldn't find anything in the docs, if it was could you please let me know how I use it.

Thanks,
Jan

**Comment by AnthonyNahas** [comment]
@vidicj you could use the child component feature of Angular like below --> 

### Template:
````html
<ngx-image-gallery #someVar
                   [images]="images2"
                   [conf]="conf2"
                   (onOpen)="galleryOpened($event)"
                   (onClose)="galleryClosed()"
                   (onImageChange)="galleryImageChanged($event)"
                   (onDelete)="deleteImage($event)">
</ngx-image-gallery>
````

now use the  **someVar** to get reference on the ngx-image-gallery component -->


### TS:
```ts
import {NgxImageGalleryComponent, GALLERY_IMAGE, GALLERY_CONF} from "ngx-image-gallery";

// your scope
export class ... {

     @ViewChild('someVar') ngxImageGallery: NgxImageGalleryComponent;

    // close gallery
    closeGallery() {
        this.ngxImageGallery.close();
    }

}
````

please make sure whether the component is used inline or not

**Comment by vidicj** [comment]
@AnthonyNahas thank you for helping me. I still haven't managed to get it to work. I am using gallery in full screen and don't understand when and how closeGallery() function is supposed to get called.

**Comment by cangec** [comment]
+1

**Comment by cangec** [comment]
@AnthonyNahas hey.  Is It possible to close the gallery on backdrop click when the gallery is full screen?
